In [ ]:
import numpy as np

unszero = np.zeros(10)
print("Array unidimensional nula: \n",unszero)
unszero = np.zeros((2, 10))
print("Array bidimensional nula: \n", unszero)
unszero = np.zeros((3,10))
print("Array tridimensional nula:\n", unszero)
unsum = np.ones(10)
print("Array unidimensional de un: \n",unsum)
unsum = np.ones((2,10))
print("Array bidimensional de uns: \n",unsum)
unsum = np.ones((3, 10))
print("Array tridimensional de uns: \n",unsum)

Array unidimensional nula: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array bidimensional nula: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Array tridimensional nula:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Array unidimensional de un: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array bidimensional de uns: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Array tridimensional de uns: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
unszero = np.zeros(10)
unsum = np.ones(6)
print("lista nula: ", unszero)
print("lista unitaria: ", unsum)

lista nula:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
lista unitaria:  [1. 1. 1. 1. 1. 1.]


In [ ]:
array1 = [i for i in range(10)]
array2 = [i + 4 for i in range(10)]

print("Array 1: ", array1)
print("Array 2: ", array2)

array2 = [i**2 for i in array2]

print("Array 2 ao quadrado: ", array2)

comp = [j > i for i, j in zip(array1, array2)]

print("Comparando Resultados: ", comp)